import 'package:get/get.dart';

import '../constants/colors.dart';
import '../models/register_meal_model.dart';

class RegisterMealController extends GetxController {
  final List<RegisterMealModel> rxlist = [
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
    RegisterMealModel(
      title: 'First existing example food\nin the database',
      kcal: '319',
      time: '60',
      gram1: '300 g',
      color1: AppColor.greenColor,
      gram2: '300 g',
      color2: AppColor.pinColor,
      gram3: '300 g',
      color3: AppColor.yellowColorColor,
    ),
  ];
}
